### ISSUE TITLE
Alternate Wedding Dress for Leah

### ISSUE THREAD

**Issue by elesea** [minervamaga/SVO-for-DSV#10]
Hello,

I am hoping to play with Diverse Stardew Valley but am having a difficulty.  From the first time I played Stardew Valley I have loved Leah.  She is always the person I marry.  I very much want to use Diverse Stardew Valley now that I have a new computer and can play with mods.  I should explain that I have Aspergers and for some reason the Desert Dove Wedding Dress for Leah triggers me.  Please, please don’t take this as a criticism of Desert Dove’s art which is amazing.  I especially adore Emily and Maru’s Wedding Dresses, they are absolutely stunning.  In fact, all of them are lovely.  But for some reason Leah’s dress from the front is all legs and I cannot cope with it.  I just get overwhelmed with legs and my brain starts hurting.  I realise this is my Aspergers flaring up, which is my problem, not yours.  

But I also noticed that you accept pull requests.  

Is there any chance to have an extra option for Leah with a different Wedding Dress, even one of the already existing ones to make my request simpler?  I do realise the sprite work would need to be redone so it is not so easy and you may not have time.  I understand if it is not possible.  Please know I do not wish to hurt anyone’s feelings.  I know the artwork is incredible and far beyond my own abilities.  Unfortunately with Aspergers our triggers aren’t always logical and can be hard to shake.  I just figured it’s worth asking in case you are able to help me.

I hope you and your loved ones are healthy and safe and as happy as possible at this crazy and difficult time.

Warmest wishes, Elese

**Comment by minervamaga** [comment]
Hello, glad to see you love the mod!  At the moment the wedding outfits aren't live in DSVO, though hopefully they will be soon.  We are not planning to include other wedding outfits right now, but are considering it for the future.  One possible alternative is to use the Butch variant, where Leah does not wear a dress but instead a suit.  You can also disable the Leah edits for the day of the wedding and then re-enable after that day in game.  I'll put a note on our list about possible other dresses for the next major version update after this one though!

Hope you are staying safe as well!

**Comment by elesea** [comment]
Dear Minervamaga,

Thank  you so much for replying to me!  I’m super excited about the prospect of Wedding Outfits and Festival Attire for DSVO!  Like bursting at the seams excited!

I was actually just about to close my issue because it’s resolved itself:  Tanpopnoko and ParadigmNomad have just added an optional file to SVO that includes an Alternate Wedding Dress for Leah.  It’s lovely!  I’ve downloaded the file so when DSVO is updated, I can use their optional .png for Leah’s Wedding Dress instead of Desert Dove’s.

I hope you are having the loveliest day,

Warmest wishes, Elese

p.s. I don’t want to press you but do you have any idea about the release date for the Wedding Outfits and Festival Attire for DSVO?  If you don’t want to say/commit yourself that’s okay I understand.  I just get very excited that’s all.  I do realise that I need to be patient because it must be a colossal amount of work and you perform so much magic for us already!
