### ISSUE TITLE
Marnie Error

### ISSUE THREAD

**Issue by mbmueff** [minervamaga/SVO-for-DSV#12]
[Content Patcher] Can't apply image patch "Diverse Stardew Valley (DSV) > Marnie Main > Code/CharacterJsons/Marnie.json > Marnie Soup" to Characters/Marnie: the FromFile file 'Characters/Marnie/Marnie_LuauSoup' doesn't exist.

Not sure what this means or what it changes but figured you might want to know about it! Thanks for all you do!!!

**Comment by AirynS** [comment]
Fixed in DSV 2.4.0 :)
