### ISSUE TITLE
Portrait & Sprite Edits

### ISSUE THREAD

**Issue by rosenclover** [minervamaga/SVO-for-DSV#9]
[DSVO Edits.zip](https://github.com/minervamaga/SVO-for-DSV/files/4044157/DSVO.Edits.zip)

Changes vanilla Caroline's hair to brown, also gives Robin a ponytail while wearing her winter hat, plus fixes the last sprite.

**EDIT**
May have gone a bit overboard but I decided to go through and make adjustments to every character that I took issue with.  This is nearly everyone, modded, and not.  Files are loosely organized.

**RE:EDIT**
Someone stop me.

Changes by Character:
Abigail - Refined Vanilla Plus portraits, tidied winter sprite inconsistencies.
Caroline - Gave Vanilla portraits and sprites brown hair, fixed and tidied multiple sprite issues.
Clint - Refined portrait by giving a properly shaped skull.
Evelyn - Complete redo of Samoan portraits (possibly label as Vietnamese or Thai), refined clothes and sprites.
George - Tweaked portraits to match Evelyn, narrowed shoulders and gave slight winter stubble.
Gunther - Adjusted skin tone, hand position, shirt colors, added gloves back
Haley - Spring default shirt is now off-the-shoulder rather than fluttery tank.
Harvey - Refined Vanilla portraits, tweaked sprites for accuracy.
Jodi - Redo of Lighter portraits (they just bugged me), changed around hijab colors.
Kent - Corrected neck posture, touched up hair, tidied winter sprite inconsistencies.
Leah - Refined (most) Native sprites.
Lewis - Added more character to Modded portraits facial features, adjusted hair coloring.
Linus - New Option! Complete overhaul as Druid.
Pam - Corrected that weird shoulder thing on Fall Indoor Rain portrait.
Penny - Evened-out hair buns, added freckles, winter blush, cleaned up inconsistencies.
Robin - Hair is now in a ponytail for Winter Outdoor portrait, updated bottom sprites.
Sandy - Another front-facing portrait group that is closer to vanilla, but not, with sprites to match.
Vincent - Gave curls poking out from Winter Outdoor hat.
Wizard - Adjusted hat, seasonal colorings, also added new cool side option with matching seasonal colors, also sprites.

**Comment by minervamaga** [comment]
Art team reviewed, not accepted at this time.  Closing.
